add hw tasks
pyropetrick/Js-practice-5 pull request #1
Opened 2022-07-31 16:11 UTC by pyropetrick

2022-08-01 14:35 UTC, igorstasiuk requested changes

2022-08-01 14:35 UTC, igorstasiuk commented on script/script.js
> +for (let key in colors) {
да, лучше без циклов =)

2022-08-01 14:35 UTC, igorstasiuk commented on script/script.js
> +for (let sum in salaries) {
еще варик через reduce попробовать , просто как доп хинт =)

2022-08-01 14:35 UTC, igorstasiuk commented on script/script.js
> +// const registr = {
тебе проще было создать переменные для промпта, а затем их в объект записать. А затем при логине проверить, сходится ли то что ввел пользователь с начальным объектом. Так будет праавильней

2022-08-01 14:35 UTC, igorstasiuk commented on script/script.js
> +// function filterScore(score) {
через объект сделать, без функции =) не зря я про мапперы рассказывал

2022-08-01 14:35 UTC, igorstasiuk commented on script/script.js
> +function findBird(object) {
тут надо было придумать как сделать так чтоб animals.bird.name не выдал ошибки, подумай, я статью не зря скидывал тогда в чат, где обработка undefined, чтоб вдруг натолкнула на мысль

2022-08-01 15:41 UTC, pyropetrick commented on script/script.js
> +// const registr = {
сначала так и хотел сделать , но потом подумал что так проще будет)

2022-08-01 16:08 UTC, pyropetrick commented on script/script.js
> +function findBird(object) {
а я ее читал, но вот нашел это решение , через условия

2022-08-01 17:09 UTC, pyropetrick commented on script/script.js
> +for (let sum in salaries) {
Это тогда нужно в массив его переводить , чуть геморней

2022-08-02 09:38 UTC, igorstasiuk requested changes

2022-08-02 09:38 UTC, igorstasiuk commented on script/script.js
> +// if ((login.username === registr.username) && (login.password === registr.password)) console.log(`Добро пожаловать, ${login.username}!`)
тут можно было вообще иметь один объект const user = { userName: '', password: '' }. При регистрации ты туда записываешь данные. А потом когда пользователь логинится, ты проверяешь user.userName === logUserName, user.password === logPassword, что-то в таком ключе

2022-08-02 09:38 UTC, igorstasiuk commented on script/script.js
> +const defaults = {
ну я тебя тут пример скидывал, как должно быть, мы вообще записи про птицу не имеем, в этом то и штука

2022-08-02 09:38 UTC, igorstasiuk commented on script/script.js
> +function findBird(object) {
по факту мы вообще не знаем про если ли птица или нет, в этом и самое главное

2022-08-02 09:38 UTC, igorstasiuk commented on script/script.js
> +const SCORE = {
const SCORE_MAP = {
0: "ноль",
1: "один",
.... }

let parsedScored = SCORE_FROM_BACK.split(':');

console.log(`SCORE_MAP[SCORE_FROM_BACK[0]]:SCORE_MAP[SCORE_FROM_BACK[1]]`;

2022-08-02 09:39 UTC, pyropetrick commented on script/script.js
> +const SCORE = {
я просто на работе дак не переписал еще все о чем мы вчера говорили

2022-08-02 11:52 UTC, igorstasiuk commented on script/script.js
> +const SCORE = {
понял, просто пришло оповещалка

2022-08-04 14:59 UTC, igorstasiuk approved these changes

2022-08-04 17:03 UTC, merged